### ISSUE TITLE
Schemas are not sent and parsed correctly

### ISSUE THREAD

**Issue by lachee10** [UnboundID/scim2#67]
When retrieving all schemas (running the test testGetSchemas within  EndpointTestCase.java) you will get the following:

`{
  "schemas" : [ "urn:ietf:params:scim:api:messages:2.0:ListResponse" ],
  "totalResults" : 2,
  "Resources" : [ {
    "schemas" : [ "urn:ietf:params:scim:schemas:core:2.0:Schema" ],
    "id" : "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
    "name" : "EnterpriseUser",
....`

However looking at sample in RFC7643 chapter 8.7.1 you will find a simple array of schemas. 

`[
  {
    "id" : "urn:ietf:params:scim:schemas:core:2.0:User",
    "name" : "User",
    "description" : "User Account",
    "attributes" : [
      {
        "name" : "userName",
        "type" : "string",
        "multiValued" : false,
        "description" : "Unique identifier for the User, typically
used by the user to directly authenticate to the service provider.
Each User MUST include a non-empty userName value.  This identifier
MUST be unique across the service provider's entire set of Users.
REQUIRED.",
        "required" : true,
        "caseExact" : false,
        "mutability" : "readWrite",
        "returned" : "default",
        "uniqueness" : "ser
....`

When retrieving all schemas from a SCIM provider that only provides the array of schemas, the client will generate an Exception.

**Comment by richardcardona** [comment]
RFC 7643 is a SCIM reference not the protocol specification. The SCIM protocol responses are in RFC 7644, in which Section 4 states:
>  /Schemas An HTTP GET to this endpoint is used to retrieve information about resource schemas supported by a SCIM service provider.  An HTTP GET to the endpoint "/Schemas" SHALL return all supported schemas in ListResponse format

**Comment by bertold** [comment]
Thank you for reporting this problem. Feel free to reopen the issue if you disagree with Richard's response.
